const DEFAULT_RETRY_COUNT: number = 3;
const ELLIPSIS_CHARACTER_COUNT: number = 3;
const MAXIMUM_RETRY_COUNT: number = 10;
const MINIMUM_API_KEY_LENGTH: number = 8;
const MINIMUM_RETRY_COUNT: number = 1;
const MINIMUM_RULE_LENGTH: number = 2;
const NOTE_BOX_CONTENT_PADDING_LENGTH: number = 2;
const NOTE_BOX_PADDING_LENGTH: number = 4;
const REDACTED_SEGMENT_LENGTH: number = 4;
const RETRY_DELAY_IN_MILLISECONDS: number = 1000;
const RULE_CONDITION_POSITION: number = 1;
const RULE_CONFIGURATION_LENGTH: number = 3;
const RULE_LEVEL_POSITION: number = 0;
const RULE_VALUE_POSITION: number = 2;
const VALIDATION_DISABLED_LEVEL: number = 0;
const VALIDATION_ERROR_LEVEL: number = 2;
const VALIDATION_WARNING_LEVEL: number = 1;

export const NUMERIC_CONSTANT: {
	readonly DEFAULT_MAX_RETRIES: number;
	readonly DEFAULT_VALIDATION_MAX_RETRIES: number;
	readonly ELLIPSIS_LENGTH: number;
	readonly MAX_RETRY_COUNT: number;
	readonly MIN_API_KEY_LENGTH: number;
	readonly MIN_RETRY_COUNT: number;
	readonly MIN_RULE_LENGTH: number;
	readonly NOTE_BOX_CONTENT_PADDING: number;
	readonly NOTE_BOX_PADDING: number;
	readonly REDACTED_LENGTH: number;
	readonly RETRY_DELAY_MS: number;
	readonly RULE_CONDITION_INDEX: number;
	readonly RULE_CONFIG_LENGTH: number;
	readonly RULE_LEVEL_INDEX: number;
	readonly RULE_VALUE_INDEX: number;
	readonly VALIDATION_LEVEL_DISABLED: number;
	readonly VALIDATION_LEVEL_ERROR: number;
	readonly VALIDATION_LEVEL_WARNING: number;
} = {
	DEFAULT_MAX_RETRIES: DEFAULT_RETRY_COUNT,
	DEFAULT_VALIDATION_MAX_RETRIES: DEFAULT_RETRY_COUNT,
	ELLIPSIS_LENGTH: ELLIPSIS_CHARACTER_COUNT,
	MAX_RETRY_COUNT: MAXIMUM_RETRY_COUNT,
	MIN_API_KEY_LENGTH: MINIMUM_API_KEY_LENGTH,
	MIN_RETRY_COUNT: MINIMUM_RETRY_COUNT,
	MIN_RULE_LENGTH: MINIMUM_RULE_LENGTH,
	NOTE_BOX_CONTENT_PADDING: NOTE_BOX_CONTENT_PADDING_LENGTH,
	NOTE_BOX_PADDING: NOTE_BOX_PADDING_LENGTH,
	REDACTED_LENGTH: REDACTED_SEGMENT_LENGTH,
	RETRY_DELAY_MS: RETRY_DELAY_IN_MILLISECONDS,
	RULE_CONDITION_INDEX: RULE_CONDITION_POSITION,
	RULE_CONFIG_LENGTH: RULE_CONFIGURATION_LENGTH,
	RULE_LEVEL_INDEX: RULE_LEVEL_POSITION,
	RULE_VALUE_INDEX: RULE_VALUE_POSITION,
	VALIDATION_LEVEL_DISABLED: VALIDATION_DISABLED_LEVEL,
	VALIDATION_LEVEL_ERROR: VALIDATION_ERROR_LEVEL,
	VALIDATION_LEVEL_WARNING: VALIDATION_WARNING_LEVEL,
} as const;
